//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryNumber20App.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood
    {
        public int BloodId { get; set; }
        public int PatientId { get; set; }
        public string Barcode { get; set; }
        public System.DateTime BloodDateTime { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
